"""version 2

Revision ID: a1511ad56dbb
Revises: f1be72c16d39
Create Date: 2024-02-23 19:42:09.403468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1511ad56dbb'
down_revision: Union[str, None] = 'f1be72c16d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('patronymic_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Students', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('Students', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.add_column('Students', sa.Column('patronymic_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Students', 'patronymic_name')
    op.drop_column('Students', 'last_name')
    op.drop_column('Students', 'first_name')
    op.drop_table('Invites')
    # ### end Alembic commands ###
