"""version 2

Revision ID: 08d23f08c2a9
Revises: 68ef616259c0
Create Date: 2024-02-24 21:52:04.097126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d23f08c2a9'
down_revision: Union[str, None] = '68ef616259c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_groups_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('students_id', sa.Integer(), nullable=False),
    sa.Column('groups_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groups_id'], ['Groups.id'], ),
    sa.ForeignKeyConstraint(['students_id'], ['Students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('students_id', 'groups_id', name='unique_student_group')
    )
    op.add_column('Groups', sa.Column('monitor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Groups', 'Students', ['monitor_id'], ['id'])
    op.drop_constraint('Students_group_id_fkey', 'Students', type_='foreignkey')
    op.drop_column('Students', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Students', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Students_group_id_fkey', 'Students', 'Groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'Groups', type_='foreignkey')
    op.drop_column('Groups', 'monitor_id')
    op.drop_table('students_groups_association')
    # ### end Alembic commands ###
