"""version 1-1

Revision ID: f1be72c16d39
Revises: 6feacd713d3a
Create Date: 2024-02-23 19:37:26.534774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1be72c16d39'
down_revision: Union[str, None] = '6feacd713d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Students', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Students', 'Groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Students', type_='foreignkey')
    op.drop_column('Students', 'group_id')
    # ### end Alembic commands ###
